### ISSUE TITLE
Add priority shortcuts in the command list

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/FingerTips#13]
Add the following commands:
- [x] `/mc` (Critical priority) 
- [x] `/mh` (High priority) 
- [x] `/mm` (Medium priority) 
- [x] `/ml` (Low priority)

**Comment by froznxd** [comment]
I would like to take up this issue :) @ozer619

**Comment by ozer550** [comment]
Sure @soilshubham, Tell us if you need any help!!
