### ISSUE TITLE
Add numerical argument to /m command 

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/FingerTips#7]
- [x] Allow the bot to take in an optional value such as `/m 5` 
- [x] Post a message such as "Hi is anyone around to help me for 5 minutes?@here" where the number is the numerical argument passed in
- [x] If no parameter is passed in, default to 30 minutes.

**Comment by akshitarora921** [comment]
@audreyfeldroy Can I take this?

**Comment by audreyfeldroy** [comment]
Hi @akshitarora921 how's it going with this issue? if you are busy or can't take this then let us know 😄 .

**Comment by akshitarora921** [comment]
Working on it
